# Generated by Django 4.2.7 on 2023-12-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_phrase', models.CharField(max_length=200)),
                ('translated_phrase', models.CharField(max_length=200)),
                ('passed_step', models.IntegerField(choices=[(0, 'no passed'), (1, '3th day'), (2, '7th day'), (3, '30th day')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
    ]
