# Generated by Django 5.0 on 2024-01-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_alter_wordmodel_passed_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='passed_step',
            field=models.IntegerField(choices=[(0, 'no passed'), (1, '1th day'), (3, '3th day'), (7, '7th day'), (30, '30th day')], default=0),
        ),
    ]
